"""STATE_SPEECH_INPUT_START = 0
    STATE_GET_SPEECH_INPUT = 1
    STATE_CHECK_INPUT = 2
    STATE_GENERATE_ANSWER_START = 3
    STATE_GET_ANSWER = 4
    STATE_SPEECH_OUTPUT_START = 5
    STATE_SPEECH_OUTPUT_NEXT_QUESTION = 6
    STATE_QUIT = 7"""